name: GreenOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/GreenOps-Carbon-Aware-DevOps

            git pull

            pkill -f app.py || true

            cd demo_app

            nohup python3 app.py > output.log 2>&1 &
